version: '4'
services:
  backend:
    container_name: api
    image: api
    build: backend
    ports:
      - "5000 : 5000"
  frontend:
    container_name: frontend
    image: frontend
    build: frontend
    ports:
      - "3000 : 3000"
  mongo: 
    container_name: mongo
    image: mongo:latest
    ports:
      - "27018 : 27017"
