export const APARTMENT_PAY_REQUEST = "APARTMENT_PAY_REQUEST"
export const APARTMENT_PAY_SUCESS = "APARTMENT_PAY_SUCESS"
export const APARTMENT_PAY_FAIL = "APARTMENT_PAY_FAIL"

export const APARTMENT_UNPAY_REQUEST = "APARTMENT_UNPAY_REQUEST"
export const APARTMENT_UNPAY_SUCESS = "APARTMENT_UNPAY_SUCESS"
export const APARTMENT_UNPAY_FAIL = "APARTMENT_UNPAY_FAIL"

export const GET_BILL_REQUEST = "GET_BILL_REQUEST"
export const GET_BILL_SUCESS = "GET_BILL_SUCESS"
export const GET_BILL_FAIL = "GET_BILL_FAIL"
